"use strict";

const roomInputParams = {
  groupId: 1,
  signUserId: "ae85ce1015f54a00b199bcc2b176acb6",
  contractAbi: [
    {
      constant: true,
      inputs: [
        { name: "name", type: "string" },
        { name: "landlord", type: "string" },
      ],
      name: "getAppartment",
      outputs: [
        { name: "", type: "string[]" },
        { name: "", type: "string[]" },
        { name: "", type: "string[]" },
        { name: "", type: "string[]" },
        { name: "", type: "string[]" },
        { name: "", type: "uint256[]" },
      ],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "oldLoadlord", type: "string" },
        { name: "name", type: "string" },
      ],
      name: "removeLAppartment",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "name", type: "string" },
        { name: "_position", type: "string" },
        { name: "_landlord", type: "string" },
        { name: "_phone", type: "string" },
        { name: "_describe", type: "string" },
        { name: "_pricesByOneday", type: "uint256" },
      ],
      name: "setAppartment",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: true,
      inputs: [
        { name: "name", type: "string" },
        { name: "landlord", type: "string" },
      ],
      name: "getAppartmentByAandL",
      outputs: [
        { name: "", type: "string[]" },
        { name: "", type: "string[]" },
        { name: "", type: "string[]" },
        { name: "", type: "string[]" },
        { name: "", type: "string[]" },
        { name: "", type: "uint256[]" },
      ],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: true,
      inputs: [{ name: "_landlord", type: "string" }],
      name: "getAppartmentByLandlord2",
      outputs: [
        { name: "", type: "string[]" },
        { name: "", type: "string[]" },
        { name: "", type: "uint256[]" },
      ],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: true,
      inputs: [{ name: "_landlord", type: "string" }],
      name: "isExistLandlord",
      outputs: [{ name: "", type: "bool" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: true,
      inputs: [
        { name: "name", type: "string" },
        { name: "landlord", type: "string" },
      ],
      name: "getAppartmentByAandL1",
      outputs: [
        { name: "", type: "string[]" },
        { name: "", type: "string[]" },
        { name: "", type: "string[]" },
      ],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: true,
      inputs: [{ name: "_landlord", type: "string" }],
      name: "getAppartmentByLandlord1",
      outputs: [
        { name: "", type: "string[]" },
        { name: "", type: "string[]" },
        { name: "", type: "string[]" },
      ],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "_name", type: "string" },
        { name: "_position", type: "string" },
        { name: "_landlord", type: "string" },
        { name: "_phone", type: "string" },
        { name: "_describe", type: "string" },
        { name: "_pricesByOneday", type: "uint256" },
      ],
      name: "increaseAppartment",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: true,
      inputs: [{ name: "_landlord", type: "string" }],
      name: "getAppartmentByLandlord",
      outputs: [
        { name: "", type: "string[]" },
        { name: "", type: "string[]" },
        { name: "", type: "string[]" },
        { name: "", type: "string[]" },
        { name: "", type: "string[]" },
        { name: "", type: "uint256[]" },
      ],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: true,
      inputs: [{ name: "appartmentName", type: "string" }],
      name: "getAppartmentByName",
      outputs: [
        { name: "", type: "string[]" },
        { name: "", type: "string[]" },
        { name: "", type: "string[]" },
        { name: "", type: "string[]" },
        { name: "", type: "string[]" },
        { name: "", type: "uint256[]" },
      ],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: true,
      inputs: [
        { name: "name", type: "string" },
        { name: "landlord", type: "string" },
      ],
      name: "getAppartmentByAandL2",
      outputs: [
        { name: "", type: "string[]" },
        { name: "", type: "string[]" },
        { name: "", type: "uint256[]" },
      ],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [{ name: "name", type: "string" }],
      name: "removeAppartment",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: true,
      inputs: [{ name: "_name", type: "string" }],
      name: "isExistAppartment",
      outputs: [{ name: "", type: "bool" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: true,
      inputs: [],
      name: "getAllAppartment",
      outputs: [
        { name: "", type: "string[]" },
        { name: "", type: "string[]" },
        { name: "", type: "string[]" },
        { name: "", type: "string[]" },
        { name: "", type: "string[]" },
        { name: "", type: "uint256[]" },
      ],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "constructor",
    },
  ],
  contractAddress: "0xdc2b1cb510d7cb7b7b6a326d9d2621fe823af5d8",
  funcName: "",
  funcParam: [],
  useCns: false,
};

const commonInputParms = {
  groupId: 1,
  signUserId: "ae85ce1015f54a00b199bcc2b176acb6",
  contractAbi: [
    {
      constant: true,
      inputs: [{ name: "_landlord", type: "string" }],
      name: "getTypeByLandlord",
      outputs: [
        { name: "name", type: "string[]" },
        { name: "landlord", type: "string[]" },
        { name: "phone", type: "string[]" },
        { name: "position", type: "string[]" },
        { name: "describe", type: "string[]" },
        { name: "typeNum", type: "uint256[]" },
        { name: "price", type: "uint256[]" },
      ],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: true,
      inputs: [{ name: "_name", type: "string" }],
      name: "getTypeByFacility",
      outputs: [
        { name: "name", type: "string[]" },
        { name: "landlord", type: "string[]" },
        { name: "phone", type: "string[]" },
        { name: "position", type: "string[]" },
        { name: "describe", type: "string[]" },
        { name: "typeNum", type: "uint256[]" },
        { name: "price", type: "uint256[]" },
      ],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: true,
      inputs: [
        { name: "_name", type: "string" },
        { name: "_landlord", type: "string" },
      ],
      name: "getTypeByFandL",
      outputs: [
        { name: "name", type: "string[]" },
        { name: "landlord", type: "string[]" },
        { name: "phone", type: "string[]" },
        { name: "position", type: "string[]" },
        { name: "describe", type: "string[]" },
        { name: "typeNum", type: "uint256[]" },
        { name: "price", type: "uint256[]" },
      ],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: true,
      inputs: [
        { name: "position", type: "string" },
        { name: "typeNum", type: "uint256" },
      ],
      name: "isExistType",
      outputs: [{ name: "", type: "bool" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "position", type: "string" },
        { name: "typeNum", type: "uint256" },
      ],
      name: "removeType",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: true,
      inputs: [
        { name: "_name", type: "string" },
        { name: "_landlord", type: "string" },
      ],
      name: "getType",
      outputs: [
        { name: "name", type: "string[]" },
        { name: "landlord", type: "string[]" },
        { name: "phone", type: "string[]" },
        { name: "position", type: "string[]" },
        { name: "describe", type: "string[]" },
        { name: "typeNum", type: "uint256[]" },
        { name: "price", type: "uint256[]" },
      ],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "name", type: "string" },
        { name: "landlord", type: "string" },
        { name: "phone", type: "string" },
        { name: "position", type: "string" },
        { name: "describe", type: "string" },
        { name: "typeNum", type: "uint256" },
        { name: "price", type: "uint256" },
      ],
      name: "insertFacilityType",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: true,
      inputs: [{ name: "position", type: "string" }],
      name: "isExistFacility",
      outputs: [{ name: "", type: "bool" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "_landlord", type: "string" },
        { name: "_phone", type: "string" },
        { name: "_position", type: "string" },
        { name: "_describe", type: "string" },
        { name: "_typeNum", type: "uint256" },
        { name: "_price", type: "uint256" },
      ],
      name: "setType",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: true,
      inputs: [],
      name: "getAllType",
      outputs: [
        { name: "name", type: "string[]" },
        { name: "landlord", type: "string[]" },
        { name: "phone", type: "string[]" },
        { name: "position", type: "string[]" },
        { name: "describe", type: "string[]" },
        { name: "typeNum", type: "uint256[]" },
        { name: "price", type: "uint256[]" },
      ],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
  ],
  contractAddress: "0xfcb97e86daa9094d7db58d9753e3fad9d05e5ede",
  funcName: "",
  funcParam: [],
  useCns: false,
};

module.exports = {
  roomInputParams,
  commonInputParms,
};
